# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gemini.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgemini.proto\x12\x0bgeminiproto\"5\n\x10PdfUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"I\n\x11PdfUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nparsedText\x18\x03 \x01(\t\"2\n\x10UserQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\"J\n\x0eGeminiResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0epromptFeedback\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gemini_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PDFUPLOADREQUEST._serialized_start=29
  _PDFUPLOADREQUEST._serialized_end=82
  _PDFUPLOADRESPONSE._serialized_start=84
  _PDFUPLOADRESPONSE._serialized_end=157
  _USERQUERYREQUEST._serialized_start=159
  _USERQUERYREQUEST._serialized_end=209
  _GEMINIRESPONSE._serialized_start=211
  _GEMINIRESPONSE._serialized_end=285
# @@protoc_insertion_point(module_scope)
